name: CI Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image version
        run: |
          Z=1
          X=$((GITHUB_RUN_NUMBER % 10))
          Y=$(( (GITHUB_RUN_NUMBER / 10) % 10 ))
          echo "IMAGE_TAG=$Z.$Y.$X" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/artiset-assignment:${{ env.IMAGE_TAG }} .

      - name: Run basic test
        run: |
          docker run -d -p 5000:5000 --name test_container ${{ secrets.DOCKERHUB_USERNAME }}/artiset-assignment:${{ env.IMAGE_TAG }}
          sleep 5
          chmod +x test.sh
          ./test.sh
    
      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: basic-test-output
          path: test-output/result.txt

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/artiset-assignment:${{ env.IMAGE_TAG }}
      
      ## Here Start CD Pipeline to deploy on GCP
      
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Container to GCP
        run: |
          gcloud compute ssh ubuntu@instance-20260114-132435 \
            --zone=us-central1-c \
            --command="
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/artiset-assignment:${{ env.IMAGE_TAG }} &&
              docker stop app || true &&
              docker rm app || true &&
              docker run -d \
                --name app \
                -p 80:5000 \
                ${{ secrets.DOCKERHUB_USERNAME }}/artiset-assignment:${{ env.IMAGE_TAG }}
            "
